import mongoose from "mongoose";
import * as dotenv from "dotenv";
import Film from "./models/film.js";
import Quote from "./models/quote.js";

dotenv.config();

await mongoose.connect(process.env.DATABASE_URL);

await Quote.deleteMany();
await Film.deleteMany();

const films = await Film.insertMany([
  {
    title: "Le Roi Lion",
    year: 1994,
    director: "Roger Allers, Rob Minkoff",
    genre: "Animation / Aventure / Famille",
    image: "https://image.tmdb.org/t/p/original/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg",
  },
  {
    title: "Le Monde de Nemo",
    year: 2003,
    director: "Andrew Stanton, Lee Unkrich",
    genre: "Animation / Aventure / Comédie",
    image: "https://image.tmdb.org/t/p/w1280/5lc6nQc0VhWFYFbNv016xze8Jvy.jpg",
  },
  {
    title: "Toy Story",
    year: 1995,
    director: "John Lasseter",
    genre: "Animation / Aventure / Comédie",
    image: "https://image.tmdb.org/t/p/w1280/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg",
  },
  {
    title: "Terrain d'Entente",
    year: 1993,
    director: "David Mickey Evans",
    genre: "Comédie / Famille / Sport",
    image: "https://image.tmdb.org/t/p/w1280/7PYqz0viEuW8qTvuGinUMjDWMnj.jpg",
  },
  {
    title: "Titanic",
    year: 1997,
    director: "James Cameron",
    genre: "Romance / Drame / Catastrophe",
    image: "https://image.tmdb.org/t/p/w1280/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
  },
  {
    title: "Star Wars: L'Empire Contre-Attaque",
    year: 1980,
    director: "Irvin Kershner",
    genre: "Science-Fiction / Aventure / Action",
    image: "https://image.tmdb.org/t/p/w1280/nNAeTmF4CtdSgMDplXTDPOpYzsX.jpg",
  },
  {
    title: "Là-Haut",
    year: 2009,
    director: "Pete Docter, Bob Peterson",
    genre: "Animation / Aventure / Comédie",
    image: "https://image.tmdb.org/t/p/w1280/mFvoEwSfLqbcWwFsDjQebn9bzFe.jpg",
  },
  {
    title: "Jurassic Park",
    year: 1993,
    director: "Steven Spielberg",
    genre: "Science-Fiction / Aventure / Thriller",
    image: "https://image.tmdb.org/t/p/w1280/bRKmwU9eXZI5dKT11Zx1KsayiLW.jpg",
  },
  {
    title: "Retour vers le Futur",
    year: 1985,
    director: "Robert Zemeckis",
    genre: "Science-Fiction / Comédie / Aventure",
    image: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/vN5B5WgYscRGcQpVhHl6p9DDTP0.jpg",
  },
  {
    title: "Top Gun",
    year: 1986,
    director: "Tony Scott",
    genre: "Action / Drame",
    image: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/xUuHj3CgmZQ9P2cMaqQs4J0d4Zc.jpg",
  },
  {
    title: "Les Tortues Ninja",
    year: 1990,
    director: "Steve Barron",
    genre: "Action / Aventure / Fantaisie",
    image: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/shfAU6xIIEAEtsloIT3n9Fscz2E.jpg",
  },
  {
    title: "The Dark Knight : Le Chevalier Noir",
    year: 2008,
    director: "Christopher Nolan",
    genre: "Action / Thriller / Super-héros",
    image: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
  },
  {
    title: "Terminator",
    year: 1984,
    director: "James Cameron",
    genre: "Science-Fiction / Action / Thriller",
    image: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/hzXSE66v6KthZ8nPoLZmsi2G05j.jpg",
  },
  {
    title: "Harry Potter à l'École des Sorciers",
    year: 2001,
    director: "Chris Columbus",
    genre: "Fantaisie / Aventure / Famille",
    image: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg",
  },
  {
    title: "Beetlejuice",
    year: 1988,
    director: "Tim Burton",
    genre: "Comédie / Fantaisie / Horreur",
    image: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/nnl6OWkyPpuMm595hmAxNW3rZFn.jpg",
  },
  {
    title: "Frankenstein",
    year: 2015,
    director: "Bernard Rose",
    genre: "Horreur / Thriller",
    image: "https://image.tmdb.org/t/p/original/53r1Wp8pdDzN4hA1WZyLBMDjMiX.jpg",
  },
  {
    title: "Les Gardiens de la Galaxie Vol. 2",
    year: 2017,
    director: "James Gunn",
    genre: "Science-fiction / Action",
    image: "https://image.tmdb.org/t/p/original/tTnDWIADl5FbpxHBO07IQCNxyb9.jpg",
  },
  {
    title: "Black Panther",
    year: 2018,
    director: "Ryan Coogler",
    genre: "Action / Super-héros",
    image: "https://image.tmdb.org/t/p/original/g94IcdzPswTYl1ISdgn2EwvaZtt.jpg",
  },
  {
    title: "Macadam Cowboy",
    year: 1969,
    director: "John Schlesinger",
    genre: "Drame",
    image: "https://image.tmdb.org/t/p/original/yoom7CNgdomR7tn0T9GOdHYY51u.jpg",
  },
  {
    title: "Jerry Maguire",
    year: 1996,
    director: "Cameron Crowe",
    genre: "Drame / Romance",
    image: "https://image.tmdb.org/t/p/original/cvObzfTrrSccb8npb2ltB7rV2cT.jpg",
  },
  {
    title: "Shining",
    year: 1980,
    director: "Stanley Kubrick",
    genre: "Horreur / Thriller",
    image: "https://image.tmdb.org/t/p/original/cnniZQGtjK8kh2tsjih4GtkX6bl.jpg",
  },
  {
    title: "Wayne's World",
    year: 1992,
    director: "Penelope Spheeris",
    genre: "Comédie",
    image: "https://image.tmdb.org/t/p/original/R8Q9qIl51SHtcX5oWSBbz4YhQV.jpg",
  },
  {
    title: "Scarface",
    year: 1983,
    director: "Brian De Palma",
    genre: "Crime / Drame",
    image: "https://image.tmdb.org/t/p/original/eGctboDIdxBSxZIcF8iLc8gebd5.jpg",
  },
  {
    title: "Iron Man",
    year: 2008,
    director: "Jon Favreau",
    genre: "Action / Super-héros",
    image: "https://image.tmdb.org/t/p/original/kNKUCNLu1lZDGAHOBEHxR6psYHx.jpg",
  },
  {
    title: "300",
    year: 2006,
    director: "Zack Snyder",
    genre: "Action / Guerre",
    image: "https://image.tmdb.org/t/p/original/hGZ9sDGcekhJUFmu3NnOhRT8uQS.jpg",
  },
  {
    title: "Des Hommes d'Honneur",
    year: 1992,
    director: "Rob Reiner",
    genre: "Drame",
    image: "https://image.tmdb.org/t/p/original/vsjxwIGaA8GP79pgtv6dqRhRsPu.jpg",
  },
  {
    title: "Star Wars: Un Nouvel Espoir",
    year: 1977,
    director: "George Lucas",
    genre: "Science-fiction",
    image: "https://image.tmdb.org/t/p/original/rLi9cokiFU20mLUPvQ0IRok3ELY.jpg",
  },
  {
    title: "Quand Harry Rencontre Sally",
    year: 1989,
    director: "Rob Reiner",
    genre: "Comédie Romantique",
    image: "https://image.tmdb.org/t/p/original/9pPRS02vf7sRYmmGtRERFspiIZO.jpg",
  },
  {
    title: "Peter Pan",
    year: 1953,
    director: "Clyde Geronimi, Wilfred Jackson, Hamilton Luske",
    genre: "Animation / Fantaisie",
    image: "https://image.tmdb.org/t/p/w600_and_h900_face/lsNXA11gQZbRfpYf6AXZzj3nEsY.jpg",
  },
]);

const quotes = [
  // Bloc 1 (joie)
  { text: "Hakuna Matata !", emotion: "joie", film: films[0]._id },
  { text: "Continue de nager.", emotion: "joie", film: films[1]._id },
  { text: "Vers l'infini et au-delà !", emotion: "joie", film: films[2]._id },
  { text: "Tu me tues, Smalls !", emotion: "joie", film: films[3]._id },
  { text: "Je suis le roi du monde !", emotion: "joie", film: films[4]._id },
  { text: "Ne me dites jamais les probabilités.", emotion: "joie", film: films[5]._id },
  { text: "L'aventure est là-bas !", emotion: "joie", film: films[6]._id },
  { text: "La vie trouve toujours un chemin.", emotion: "joie", film: films[7]._id },
  { text: "Nom de Zeus !", emotion: "joie", film: films[8]._id },
  { text: "J'ai besoin de vitesse.", emotion: "joie", film: films[9]._id },
  { text: "Cowabunga !", emotion: "joie", film: films[10]._id },
  { text: "Pourquoi si sérieux ?", emotion: "joie", film: films[11]._id },
  { text: "Je reviendrai.", emotion: "joie", film: films[12]._id },
  { text: "Tu es un sorcier, Harry.", emotion: "joie", film: films[13]._id },
  { text: "C'est l'heure du spectacle !", emotion: "joie", film: films[14]._id },
  { text: "Il est vivant !", emotion: "joie", film: films[15]._id },
  { text: "Je s'appelle Groot.", emotion: "joie", film: films[16]._id },
  { text: "Wakanda pour toujours !", emotion: "joie", film: films[17]._id },
  { text: "Je marche ici !", emotion: "joie", film: films[18]._id },
  { text: "Montre-moi l'argent !", emotion: "joie", film: films[19]._id },
  { text: "Me voilà !", emotion: "joie", film: films[20]._id },
  { text: "La fête continue, Wayne !", emotion: "joie", film: films[21]._id },
  { text: "Dis bonjour à mon petit ami !", emotion: "joie", film: films[22]._id },
  { text: "Je suis Iron Man.", emotion: "joie", film: films[23]._id },
  { text: "C'est Sparte !", emotion: "joie", film: films[24]._id },
  { text: "Vous ne pouvez pas supporter la vérité !", emotion: "joie", film: films[25]._id },
  { text: "Que la Force soit avec toi.", emotion: "joie", film: films[26]._id },
  { text: "Je prendrai la même chose qu'elle.", emotion: "joie", film: films[27]._id },
  { text: "Tous les enfants savent voler.", emotion: "joie", film: films[28]._id },

  // Bloc 2 (tristesse)
  { text: "Je suis content que tu sois là avec moi.", emotion: "tristesse", film: films[0]._id },
  { text: "Je vois des gens morts.", emotion: "tristesse", film: films[1]._id },
  { text: "Pardon, Wilson !", emotion: "tristesse", film: films[2]._id },
  { text: "Ne lâche pas.", emotion: "tristesse", film: films[3]._id },
  { text: "Tu as été pesé.", emotion: "tristesse", film: films[4]._id },
  { text: "Je ne suis pas un homme intelligent.", emotion: "tristesse", film: films[5]._id },
  { text: "Rosebud.", emotion: "tristesse", film: films[6]._id },
  { text: "Au revoir, vieil ami.", emotion: "tristesse", film: films[7]._id },
  { text: "J'ai peur.", emotion: "tristesse", film: films[8]._id },
  { text: "Tu vas me manquer.", emotion: "tristesse", film: films[9]._id },
  { text: "Pourquoi es-tu parti ?", emotion: "tristesse", film: films[10]._id },
  { text: "Il est parti.", emotion: "tristesse", film: films[11]._id },
  { text: "Il n'y a pas de place pour moi.", emotion: "tristesse", film: films[12]._id },
  { text: "Ce n'était pas suffisant.", emotion: "tristesse", film: films[13]._id },
  { text: "Je t'ai déçu.", emotion: "tristesse", film: films[14]._id },
  { text: "J'ai essayé.", emotion: "tristesse", film: films[15]._id },
  { text: "Je ne voulais pas ça.", emotion: "tristesse", film: films[16]._id },
  { text: "Je ne peux pas faire ça seul.", emotion: "tristesse", film: films[17]._id },
  { text: "Reste, s'il te plaît.", emotion: "tristesse", film: films[18]._id },
  { text: "Pardonne-moi.", emotion: "tristesse", film: films[19]._id },
  { text: "Qu'ai-je fait ?", emotion: "tristesse", film: films[20]._id },
  { text: "Je me souviens de tout.", emotion: "tristesse", film: films[21]._id },
  { text: "Je l'ai perdue.", emotion: "tristesse", film: films[22]._id },
  { text: "Ça fait mal.", emotion: "tristesse", film: films[23]._id },
  { text: "Rien ne change jamais.", emotion: "tristesse", film: films[24]._id },
  { text: "Tu as dit que tu reviendrais.", emotion: "tristesse", film: films[25]._id },
  { text: "C'est un adieu.", emotion: "tristesse", film: films[26]._id },
  { text: "Je m'effondre.", emotion: "tristesse", film: films[27]._id },
  { text: "J'aimerais que ce soit différent.", emotion: "tristesse", film: films[28]._id },

  // Bloc 3 (amour)
  { text: "Tu me complètes.", emotion: "amour", film: films[0]._id },
  { text: "À tes ordres.", emotion: "amour", film: films[1]._id },
  { text: "Je ne te lâcherai jamais.", emotion: "amour", film: films[2]._id },
  { text: "Voici en te regardant, gamin.", emotion: "amour", film: films[3]._id },
  { text: "Je suis à toi.", emotion: "amour", film: films[4]._id },
  { text: "Pour moi, tu es parfait.", emotion: "amour", film: films[5]._id },
  { text: "Toujours.", emotion: "amour", film: films[6]._id },
  { text: "Je te choisis.", emotion: "amour", film: films[7]._id },
  { text: "Tu m'as eu dès bonjour.", emotion: "amour", film: films[8]._id },
  { text: "Je t'aime. Je sais.", emotion: "amour", film: films[9]._id },
  { text: "Je brûle pour toi.", emotion: "amour", film: films[10]._id },
  { text: "Je t'ai trouvé.", emotion: "amour", film: films[11]._id },
  { text: "Tu me rends entier.", emotion: "amour", film: films[12]._id },
  { text: "Reste avec moi.", emotion: "amour", film: films[13]._id },
  { text: "Je t'attendrai.", emotion: "amour", film: films[14]._id },
  { text: "Tu es ma personne.", emotion: "amour", film: films[15]._id },
  { text: "Je suis amoureux.", emotion: "amour", film: films[16]._id },
  { text: "Prends ma main.", emotion: "amour", film: films[17]._id },
  { text: "Pour toujours.", emotion: "amour", film: films[18]._id },
  { text: "Reviens vers moi.", emotion: "amour", film: films[19]._id },
  { text: "Tu es tout.", emotion: "amour", film: films[20]._id },
  { text: "Tu me sauves.", emotion: "amour", film: films[21]._id },
  { text: "Seulement toi.", emotion: "amour", film: films[22]._id },
  { text: "Je ne partirai pas.", emotion: "amour", film: films[23]._id },
  { text: "Tu comptes pour moi.", emotion: "amour", film: films[24]._id },
  { text: "Je crois en nous.", emotion: "amour", film: films[25]._id },
  { text: "Tu en vaux la peine.", emotion: "amour", film: films[26]._id },
  { text: "Mon cœur est à toi.", emotion: "amour", film: films[27]._id },
  { text: "Ne pars pas.", emotion: "amour", film: films[28]._id },

  // Bloc 4 (nostalgie)
  { text: "Rien ne vaut son chez-soi.", emotion: "nostalgie", film: films[0]._id },
  { text: "Je serai juste là.", emotion: "nostalgie", film: films[1]._id },
  { text: "Vous ne passerez pas !", emotion: "nostalgie", film: films[2]._id },
  { text: "Téléphone maison.", emotion: "nostalgie", film: films[3]._id },
  { text: "Je me sens heureux !", emotion: "nostalgie", film: films[4]._id },
  { text: "Des routes ? Là où nous allons, nous n'avons pas besoin de routes.", emotion: "nostalgie", film: films[5]._id },
  { text: "Cours, Forrest, cours !", emotion: "nostalgie", film: films[6]._id },
  { text: "Ressaisis-toi !", emotion: "nostalgie", film: films[7]._id },
  { text: "C'est un piège !", emotion: "nostalgie", film: films[8]._id },
  { text: "Je n'oublierai jamais ça.", emotion: "nostalgie", film: films[9]._id },
  { text: "C'est chez moi.", emotion: "nostalgie", film: films[10]._id },
  { text: "On a passé du bon temps.", emotion: "nostalgie", film: films[11]._id },
  { text: "Je me souviens de ça.", emotion: "nostalgie", film: films[12]._id },
  { text: "Ça me semble familier.", emotion: "nostalgie", film: films[13]._id },
  { text: "On était inarrêtables.", emotion: "nostalgie", film: films[14]._id },
  { text: "Tout était plus simple.", emotion: "nostalgie", film: films[15]._id },
  { text: "J'aimerais qu'on puisse revenir en arrière.", emotion: "nostalgie", film: films[16]._id },
  { text: "Ça me rappelle quelque chose.", emotion: "nostalgie", film: films[17]._id },
  { text: "Il était une fois.", emotion: "nostalgie", film: films[18]._id },
  { text: "Il y a longtemps.", emotion: "nostalgie", film: films[19]._id },
  { text: "Pas encore.", emotion: "nostalgie", film: films[20]._id },
  { text: "J'ai déjà entendu ça.", emotion: "nostalgie", film: films[21]._id },
  { text: "Tu te souviens ?", emotion: "nostalgie", film: films[22]._id },
  { text: "On dirait que c'était hier.", emotion: "nostalgie", film: films[23]._id },
  { text: "Toujours la même histoire.", emotion: "nostalgie", film: films[24]._id },
  { text: "Ça ressemble à la maison.", emotion: "nostalgie", film: films[25]._id },
  { text: "Comme au bon vieux temps.", emotion: "nostalgie", film: films[26]._id },
  { text: "On se retrouve.", emotion: "nostalgie", film: films[27]._id },
  { text: "Bonjour vieil ami.", emotion: "nostalgie", film: films[28]._id },

  // Bloc 5 (anxiété)
  { text: "J'ai un mauvais pressentiment.", emotion: "anxiété", film: films[0]._id },
  { text: "Ils arrivent.", emotion: "anxiété", film: films[1]._id },
  { text: "Nous ne sommes pas seuls.", emotion: "anxiété", film: films[2]._id },
  { text: "Ne bouge pas.", emotion: "anxiété", film: films[3]._id },
  { text: "Reste silencieux.", emotion: "anxiété", film: films[4]._id },
  { text: "C'est derrière toi.", emotion: "anxiété", film: films[5]._id },
  { text: "Cours !", emotion: "anxiété", film: films[6]._id },
  { text: "Quelque chose ne va pas.", emotion: "anxiété", film: films[7]._id },
  { text: "Je ne peux pas respirer.", emotion: "anxiété", film: films[8]._id },
  { text: "Ils nous observent.", emotion: "anxiété", film: films[9]._id },
  { text: "On doit partir maintenant.", emotion: "anxiété", film: films[10]._id },
  { text: "Ne regarde pas en bas.", emotion: "anxiété", film: films[11]._id },
  { text: "Continue d'avancer.", emotion: "anxiété", film: films[12]._id },
  { text: "Ce n'est pas bon.", emotion: "anxiété", film: films[13]._id },
  { text: "Nous sommes piégés.", emotion: "anxiété", film: films[14]._id },
  { text: "Je ne suis pas prêt.", emotion: "anxiété", film: films[15]._id },
  { text: "Je ne peux pas faire ça.", emotion: "anxiété", film: films[16]._id },
  { text: "J'entends quelque chose.", emotion: "anxiété", film: films[17]._id },
  { text: "C'est trop calme.", emotion: "anxiété", film: films[18]._id },
  { text: "Ne te retourne pas.", emotion: "anxiété", film: films[19]._id },
  { text: "On perd du temps.", emotion: "anxiété", film: films[20]._id },
  { text: "Ils savent qu'on est là.", emotion: "anxiété", film: films[21]._id },
  { text: "Retiens ta respiration.", emotion: "anxiété", film: films[22]._id },
  { text: "Bouge !", emotion: "anxiété", film: films[23]._id },
  { text: "Nous sommes encerclés.", emotion: "anxiété", film: films[24]._id },
  { text: "Je pense qu'on est les prochains.", emotion: "anxiété", film: films[25]._id },
  { text: "Il n'y a pas d'échappatoire.", emotion: "anxiété", film: films[26]._id },
  { text: "Ça se passe maintenant.", emotion: "anxiété", film: films[27]._id },
  { text: "Ne lâche pas.", emotion: "anxiété", film: films[28]._id },
];

await Quote.insertMany(quotes);

console.log("Seed terminé !");
await mongoose.disconnect();
process.exit();
